"""
NAME
       5_Abstracts.py
VERSION
        [1.0]
AUTHOR
        Melissa Mayén Quiroz
        
DESCRIPTION
        Primera parte:
        La función 'busqueda' nos pide como parámetros (1)el path donde deseamos guardar nuestro archivo de salida y 
        algunos términos necesarios para la búsqueda: (2)el nombre del autor o autora a buscar y (3)(4)dos términos 
        que esperamos se encuentre en el título; y nos regresará un archivo en el path especificado que contenga los IDs
        de los artículos encontrados.  
        Segunda parte:
        La función 'abstracts_citas' nos pide como parámetros (1)el path del archivo (para lectura) que contenga los IDs de 
        los artículos encontrados y (2)el path donde deseamos guardar nuestro archivo de salida; y nos regresará un archivo 
        en el path especificado que contenga los abstracts de los artículos y (si se nencuentran) los IDs de los artículos 
        que lo citan.
INPUT
        Primera parte:
        -Path donde deseamos guardar el archivo de salida
        -Nombre del autor o autora a buscar
        -Término a buscar en el título 
        -Término alternativo a buscar en el título 
        Segunda parte:
        -Path desde donde queremos leer el archivo de IDs
        -Path donde deseamos guardar el archivo de salida
OUTPUT
        -Archivo (con el path especificado por el usuario) que contiene los IDs de los artículos encontrados.
        -Archivo (con el path especificado por el usuario) que contiene los abtracts
EXAMPLES
        Input
                Primera parte: 
                busqueda("C:\\Users\\Melissa\\Downloads\\archivo_ids","Cevallos", "microbiota","signaling")
                Segunda parte:
                abstracts_citas("C:\\Users\\Melissa\\Downloads\\archivo_ids", "C:\\Users\\Melissa\\Downloads\\abstracts")
        Output
                Primera parte:
                Archivo de salida C:\\Users\\Melissa\\Downloads\\archivo_ids 
                <34385401, 33468700, 28798125, 28409539>

                Segunda parte:
                Archivo de salida C:\\Users\\Melissa\\Downloads\\abstracts

               < ID:     34385401
                Abstract:       
                1. Science. 2021 Aug 13;373(6556):813-818. doi: 10.1126/science.aba3683.

                High-fat diet-induced colonocyte dysfunction escalates microbiota-derived
                trimethylamine N-oxide.

                Yoo W(1)(2), Zieba JK(1)(2), Foegeding NJ(2)(2), Torres TP(1)(2), Shelton
                CD(1)(2), Shealy NG(1)(2), Byndloss AJ(3), Cevallos SA(3), Gertz E(4)(5)(6),
                Tiffany CR(3), Thomas JD(1)(2), Litvak Y(6)(3)(7), Nguyen H(3), Olsan
                EE(3)(3)(4), Bennett BJ(4)(5)(6), Rathmell JC(1)(2)(1)(8)(9), Major
                AS(1)(5)(2)(8)(10), Bäumler AJ(11), Byndloss MX(12)(1)(8)(9).

                Author information: 
                (1)Vanderbilt Institute for Infection, Immunology, and Inflammation, Vanderbilt
                University Medical Center, Nashville, TN 37232, USA.
                (2)Department of Pathology, Microbiology, and Immunology, Vanderbilt University
                Medical Center, Nashville, TN 37232, USA.
                (...)
                A Western-style, high-fat diet promotes cardiovascular disease, in part because
                it is rich in choline, which is converted to trimethylamine (TMA) by the gut
                microbiota. However, whether diet-induced changes in intestinal physiology can
                alter the metabolic capacity of the microbiota remains unknown. Using a mouse
                model of diet-induced obesity, we show that chronic exposure to a high-fat diet
                escalates Escherichia coli choline catabolism by altering intestinal epithelial
                physiology. A high-fat diet impaired the bioenergetics of mitochondria in the
                colonic epithelium to increase the luminal bioavailability of oxygen and nitrate,
                thereby intensifying respiration-dependent choline catabolism of E. coli In turn,
                E. coli choline catabolism increased levels of circulating trimethlamine N-oxide,
                which is a potentially harmful metabolite generated by gut microbiota.

                Copyright © 2021 The Authors, some rights reserved; exclusive licensee American
                Association for the Advancement of Science. No claim to original U.S. Government 
                Works.

                DOI: 10.1126/science.aba3683 
                PMCID: PMC8506909
                PMID: 34385401  [Indexed for MEDLINE]

                No se encontraron citas


                ID:     33468700
                Abstract:       
                1. mBio. 2021 Jan 19;12(1). pii: e03227-20. doi: 10.1128/mBio.03227-20.

                5-Aminosalicylic Acid Ameliorates Colitis and Checks Dysbiotic Escherichia coli
                Expansion by Activating PPAR-γ Signaling in the Intestinal Epithelium.

                Cevallos SA(1), Lee JY(1), Velazquez EM(1), Foegeding NJ(2)(3), Shelton CD(2)(3),
                Tiffany CR(1), Parry BH(1), Stull-Lane AR(1), Olsan EE(1), Savage HP(1), Nguyen
                H(1), Ghanaat SS(1), Byndloss AJ(1), Agu IO(1), Tsolis RM(1), Byndloss
                MX(#)(2)(3), Bäumler AJ(#)(4).
                (...)
                Citas:
                ['8506909', '8283795', '8214737']


                ID:     28798125
                Abstract:       
                1. Science. 2017 Aug 11;357(6351):570-575. doi: 10.1126/science.aam9949.

                Microbiota-activated PPAR-γ signaling inhibits dysbiotic Enterobacteriaceae
                expansion.
                (...) >
GITHUB 
        https://github.com/Melii99/python_class/tree/master/Tareas/5_Abstracts.py
       
"""

'''
Primera parte:
Definimos la función busqueda, que nos regresará un archivo en el path especificado que contenga los IDs de los artículos encontrados.  
Parámetros:
        (1)Path donde deseamos guardar el archivo de salida
        (2)Nombre del autor o autora a buscar
        (3)Término a buscar en el título 
        (4)Término alternativo a buscar en el título
'''

def busqueda(path1, autor, palabra1, palabra2):

        #Realizamos la importación de librerías
        from Bio import Entrez
        #proporcionamos un email
        Entrez.email = "mmayen@lcg.unam.mx"

        #Abrimos un archivo en modo escritura (con el path proporcionado)
        archivo = open(path1, "w")

        #Realizamos la búsqueda del autor y los términos proporcionados
        termino = f'(({autor}[AUTH]) AND ({palabra1}[Title] OR {palabra2}[Title]))'
        handle = Entrez.esearch(db="pubmed", term=termino)
        #Guardamos los IDs encontrados
        ids = Entrez.read(handle)
        #Modificamos la lista de ids para leerla como string
        ids_string = str(ids["IdList"])
        #Removemos algunos caracteres para obtener unicamente los ids (separados por una coma)
        ids_string = ids_string.replace('[','')
        ids_string = ids_string.replace(']','')
        ids_string = ids_string.replace("'","")
        ids_string = ids_string.replace(' ','')

        #Escribimos los IDs en el archivo (unicamente los ids separados por una coma)
        archivo.write(ids_string)
        #Cerramos el archivo
        archivo.close()
        #Cerramos el handle
        handle.close()


#Realizamos una búsqueda con la función 'busqueda'
busqueda("C:\\Users\\Melissa\\Downloads\\archivo_ids","Cevallos", "microbiota","signaling")


'''
Segunda parte:
Definimos la funcion abtracts_citas, que nos regresará un archivo en el path especificado que contenga los 
abstracts de los artículos y (si se nencuentran) los IDs de los artículos que lo citan.
Parámtros:
        (1)Path desde donde queremos leer el archivo de IDs
        (2)Path donde deseamos guardar el archivo de salida
'''

def abstracts_citas(archivo_ids, path2):

        #Realizamos la importación de librerías
        from Bio import Entrez
        #proporcionamos un email
        Entrez.email = "mmayen@lcg.unam.mx"

        #Leemos el contenido del archivo de IDs (desde el path proporcionado)
        archivo = open(archivo_ids, "r")
        #Hacemos un split para crear una lista que contenga los IDs
        ids_list = archivo.read().split(',')
        #Abrimos un archivo en modo escritura (con el path proporcionado)
        archivo2 = open(path2, "w")

        #Realizamos un for para cada ID que contiene nuestra lista de IDs
        for ids in ids_list: 
                #Escribimos en el archivo el ID al que pertenece
                archivo2.write("ID:\t" + ids)

                #Realizamos la búsqueda de los abstracts 
                fetch_handle = Entrez.efetch(db="pubmed", id=ids, rettype="abstract", retmode="text")
                #Guardamos el abstract 
                abstract = fetch_handle.read()
                fetch_handle.close()
                #Escribimos el abstract en el archivo
                archivo2.write("\nAbstract:\t" + abstract )

                #Realizamos la búsqueda de los links (IDs de los artículos que citan al artículo)
                results = Entrez.read(Entrez.elink(dbfrom="pubmed", db="pmc", LinkName="pubmed_pmc_refs", from_uid=ids))
                #Si se encuentran citas se guardan los IDs
                if len(results[0]['LinkSetDb']) >0:
                        pmc_ids = [link["Id"] for link in results[0]['LinkSetDb'][0]['Link']]
                        #Escribimos los IDs de las citas en el archivo
                        archivo2.write('Citas:\n' + str(pmc_ids) + "\n\n\n")
                else:
                        #En caso de no encontrar citas lo especificamos en el archivo
                        archivo2.write("No se encontraron citas\n\n\n")

        #Cerramos el archivo
        archivo2.close() 


#Con la función 'abstracts_citas' leemos el archivo de salida de la búsqueda y creamos un nuevo archivo 'abstracts'
abstracts_citas("C:\\Users\\Melissa\\Downloads\\archivo_ids", "C:\\Users\\Melissa\\Downloads\\abstracts")